### ISSUE TITLE
so question in k8s/netstat.yaml 

### ISSUE THREAD

**Issue by jjmengze** [Ci-Jie/kubereum#2]
我在底下加了這個就不會一直跳錯誤訊息跟崩潰。
```
        image:  cijie/kubereum-netstat:0.1.0
         command:
         - "/bin/sh"
         args:
         - "-c"
         - "while :; do sleep 3600; done"
```
